create table CUSTOMERS(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
name varchar,
surname varchar,
age int,
phone_number varchar
);

insert into CUSTOMERS( name, surname, age, phone_number)
values ('Pavel','Pavlov', 35, '+79006005040'),
       ('Ivan', 'Ivanov', 34, '+7(3812)906050'),
       ('Petr', 'Petrov', 24, '+7(495)9005040'),
       ('Alexey','Alexeev', 35, '+79006005040');

create table ORDERS(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
date date,
customer_id  int references customers (id),
product_name varchar,
amount int
);

insert into ORDERS ( date, customer_id, product_name, amount)
values ('06.10.22', 1, 'Notebook Asus',   3),
       ('07.10.22', 2, 'Notebook Acer',   2),
       ('08.10.22', 2, 'Notebook Huawei', 8),
       ('09.10.22', 2, 'Notebook MacBook',2),
       ('10.10.22', 3, 'Notebook Huawei', 8),
       ('11.10.22', 4, 'Notebook Xiaomi', 2),
       ('12.10.22', 3, 'Notebook Huawei', 8);